# Generated by Django 5.0.6 on 2024-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
